### ISSUE TITLE
Issue with Block Placement Order and Code Execution Order

### ISSUE THREAD

**Issue by ghost** [alu454/BlocklySpot#2]
I have noticed an issue with the current behavior of the blocks in this project. It seems that blocks can be placed anywhere on the screen, regardless of their logical placement in the code flow. This leads to a problem where the order of block execution does not match the order of the code generated.

To ensure correct code execution, it would be beneficial to enforce a specific order of blocks by design or by restricting block placement. Currently, if a block is placed above the initialization block on the screen, its Python code will be printed before the initialization block, which can result in commands above the initialization block not being able to run.

One possible solution is to force blocks to be attached to or inside the initialization block, ensuring that code stays in the desired order. This can be achieved by using the .setCheck() method on the block to limit the types of blocks that can be connected.

In addition, it may also be helpful to move some of the initialization code outside of a block and include it at the top of the generated code by default. This way, it is treated as common setup code that is needed each time.

**Comment by drew-bozarth** [comment]
This is a great point. You are correct in your observation of how the block placement affects the code output. One thing to note is that our project is meant to only create one string of touching blocks, so if somebody generates code with multiple separate sections of blocks, the code will not be useable. I agree it would be beneficial for the program to not allow for floating blocks, and that would be a great error-checking/handling implementation in future works. As for having the initialization code be generated automatically, this was our original approach, but we moved towards the initialization block idea because we felt it showed the user that there is a lot of setup code needed for interacting with spot and how important that block is. We also think the visual aspect of that block encapsulating all of the commands is useful to show that only things inside that block will run.
